### PR TITLE
chore: update error metrics report

### PR DESCRIPTION
**Pull request by duyhungtnn**
Fixes https://github.com/bucketeer-io/android-client-sdk/issues/136

# TODO
- [x] Track the 3xx status code as "RedirectRequestException". 
  - [x] add `response_code` via labels
- [x] Track the 413 status code as "PayloadTooLargeException"
- [x] Track 408 status code, and we should handle it as a timeout error.
- [x] Implement adding more information via labels for Unknown errors, so we don't spend too much time debugging.
  - [x]  Add `error_message` and `response_code` to the ErrorMetricsEvent labels 
- [x] Fixed could not capture response status code when The server responded with a 2xx status code and an invalid JSON response body.
# Tests
- [x] Track the 3xx status code as "RedirectRequestException"
  - [x] add `response_code` via labels
- [x] Track the 413 status code as "PayloadTooLargeException"
- [x] 408 errors, and we should handle it as a timeout error.
- [x] Implement adding more information via labels for Unknown errors, so we don't spend too much time debugging.
  - [x]  Add `error_message` and `response_code` to the ErrorMetricsEvent labels

### CODE REVIEW

**Comment by duyhungtnn** [comment]
hi @cre8ivejp , please help me to take a look on this PR. Thank you.

**Comment by cre8ivejp** [comment]
@duyhungtnn, can you remove the comments linking to the issue?
```
// https://github.com/bucketeer-io/ios-client-sdk/issues/65
```
I think we don't need them for this PR. We can just check the git history.

**Comment by duyhungtnn** [comment]
hi @cre8ivejp 
I removed a comments also I fixed one test that fail randomly.

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Pull request merged**
