### PR TITLE
chore: add sdk version to the network requests

### LINKED ISSUE #82: chore: add the sdkVersion in the requests
To help monitor the APIs by `sdkVersion`, we need to add it to the `GetEvaluations` and `RegisterEvents` APIs.

### Things to do

- Add the `sdkVersion` in the API request.

#### GetEvaluations

https://github.com/bucketeer-io/android-client-sdk/blob/main/bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/model/request/GetEvaluationsRequest.kt#L8-L13

#### RegisterEvents

https://github.com/bucketeer-io/android-client-sdk/blob/main/bucketeer/src/main/kotlin/io/bucketeer/sdk/android/internal/model/request/RegisterEventsRequest.kt#L7-L9

### PR DESCRIPTION
**Pull request by duyhungtnn**
Should close #82 
Refs: JS SDK implementation https://github.com/bucketeer-io/javascript-client-sdk/blob/5f969cf05ac96f8da406dabb3c70e4930c9f8405/src/internal/remote/ApiClient.ts#L16

### CODE REVIEW

**Comment by duyhungtnn** [comment]
hi @yshrsmz , please help me to take a look

**Review by yshrsmz — APPROVED** [review]
👍

**Comment by duyhungtnn** [comment]
@cre8ivejp please help me to take a look

**Review by cre8ivejp — APPROVED** [review]
Thank you!

**Pull request merged**
